'use client'
import { motion } from 'framer-motion'
import { useState } from 'react'

const achievements = [
  ['✦','App Development with Swift Associate Certification','Confirmed credential','A certification marking a foundation in Swift and app development.'],
  ['↗','Swift Accelerator Program','Completed / participated','Hands-on learning through the Swift Accelerator program.'],
  ['⌁','Grade 12 · American Curriculum','Current status','Currently studying at American National School, Al Ain.'],
  ['＋','Independent AP Preparation','In progress','Preparing for future AP examinations through an external pathway.'],
  ['◎','Future CS & AI Applicant','Next chapter','Preparing to pursue undergraduate study in Computer Science and AI internationally.'],
]
const projects = [
  ['01','iOS App Experiments','Swift · iOS','Swift-based learning and app development work.'],
  ['02','UI/UX Concepts','Interface · Design','Interface explorations and design thinking.'],
  ['03','Creative Technology Ideas','Concepts · Problem-solving','Ideas combining technology, design and problem-solving.'],
  ['04','Future AI Projects','Coming soon','A space for future experiments with intelligent systems.'],
]
const fade = { hidden:{opacity:0,y:18}, show:{opacity:1,y:0,transition:{duration:.55}} }

export default function Home(){
 const [dark,setDark]=useState(true); const [menu,setMenu]=useState(false)
 const scroll=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)}
 return <main className={dark?'site dark':'site'}>
  <nav className="nav"><button className="brand" onClick={()=>scroll('home')}><span className="brandMark">M</span><span>Malek Al Bikawi</span></button><div className={menu?'navLinks open':'navLinks'}>{['About','Work','Journey','Contact'].map(x=><button key={x} onClick={()=>scroll(x.toLowerCase())}>{x}</button>)}</div><div className="navActions"><button className="theme" aria-label="Toggle color theme" onClick={()=>setDark(!dark)}>{dark?'☼':'☾'}</button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button></div></nav>
  <section id="home" className="hero section"><div className="heroCopy"><motion.p initial="hidden" animate="show" variants={fade} className="eyebrow"><span className="dot"/> BASED IN AL AIN, UAE</motion.p><motion.h1 initial="hidden" animate="show" variants={fade}>Designing<br/><em>ideas</em> into apps.</motion.h1><motion.p initial="hidden" animate="show" variants={fade} className="lede">Grade 12 student, aspiring computer scientist, and Swift/iOS developer exploring AI, app design, and creative technology.</motion.p><div className="heroCtas"><button className="button primary" onClick={()=>scroll('work')}>View my work <span>↗</span></button><button className="textButton" onClick={()=>scroll('about')}>About me <span>→</span></button></div></div><motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.8}} className="heroVisual"><div className="orbit o1"/><div className="orbit o2"/><div className="visualCard"><div className="windowTop"><i/><i/><i/><small>malek.swift</small></div><div className="code"><span>01</span><p><b>let</b> idea = <strong>"useful"</strong></p><span>02</span><p><b>let</b> design = <strong>"beautiful"</strong></p><span>03</span><p><b>if</b> idea + design {'{'}</p><span>04</span><p className="indent">buildSomethingReal()</p><span>05</span><p>{'}'}</p></div><div className="codeGlow"/></div><div className="floatBadge badgeA">✦ <span>creative technology</span></div><div className="floatBadge badgeB">⌁ <span>swift / iOS</span></div></motion.div></section>
  <section id="about" className="section about"><div className="sectionLabel">01 / ABOUT</div><div className="aboutGrid"><h2>Curious by nature.<br/><span>Builder by choice.</span></h2><div><p className="largeText">I enjoy the space where logic meets creativity — turning a loose idea into something people can actually use.</p><p>I’m a Grade 12 student at American National School, Al Ain, exploring Swift, iOS development, UI/UX, AI, and the wider world of Computer Science. Through the Swift Accelerator program and my App Development with Swift Associate certification, I’ve started building a foundation for what comes next.</p><p>My goal is simple: make useful, beautiful digital experiences while learning how technology can help people.</p></div></div><div className="explore"><h3>What I’m exploring</h3><div className="chips">{['iOS Development','Swift','Artificial Intelligence','UI/UX Design','Creative Technology','Computer Science','Mathematics'].map(x=><span key={x}>{x} <b>↗</b></span>)}</div></div></section>
  <section id="work" className="section work"><div className="sectionLabel">02 / SELECTED WORK</div><div className="sectionIntro"><h2>Small experiments.<br/><span>Big direction.</span></h2><p>A growing collection of learning, design, and app-development work. More details coming as the ideas become real.</p></div><div className="projectGrid">{projects.map(([num,title,meta,desc],i)=><motion.article whileHover={{y:-6}} key={title} className={'project p'+i}><div className="projectArt"><span>{num}</span><div className="shape"/><div className="artLabel">{i===0?'swift()':i===1?'frame / feeling':i===2?'idea → impact':'AI / next'}</div></div><div className="projectMeta"><div><p>{meta}</p><h3>{title}</h3></div><span className="arrow">↗</span></div><p className="projectDesc">{desc} <b>Details coming soon.</b></p></motion.article>)}</div></section>
  <section id="achievements" className="section achievements"><div className="sectionLabel">03 / CREDENTIALS</div><div className="sectionIntro"><h2>Proof of progress.</h2><p>Milestones that reflect where I’ve been — and the direction I’m heading.</p></div><div className="achievementList">{achievements.map(([icon,title,tag,desc],i)=><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade} className="achievement" key={title}><span className="achievementIcon">{icon}</span><div className="achievementBody"><div className="tag">{tag}</div><h3>{title}</h3><p>{desc}</p></div><span className="achievementNum">0{i+1}</span></motion.div>)}</div></section>
  <section id="journey" className="section journey"><div className="sectionLabel">04 / THE JOURNEY</div><div className="journeyGrid"><div><h2>Always learning.<br/><span>Always moving.</span></h2><p className="largeText">This is the beginning of a serious tech-and-design career — one thoughtful project at a time.</p></div><div className="timeline">{['American-curriculum student','Explored technology, app development and design','Swift Accelerator program','App Development with Swift Associate certification','Grade 12 + international university preparation','Future: study Computer Science / AI and create technology that helps people'].map((x,i)=><div className="timeItem" key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div></div><div className="learning"><h3>Currently learning</h3><div>{['Advanced math / precalculus','Computer Science foundations','Swift and iOS development','AI concepts','Design and UI/UX'].map(x=><span key={x}>+ {x}</span>)}</div></div></section>
  <section id="contact" className="section contact"><div className="sectionLabel">05 / SAY HELLO</div><div className="contactGrid"><div><h2>Have an idea?<br/><em>Let’s talk.</em></h2><p>I’m always interested in thoughtful conversations about technology, design, and what’s next.</p><div className="contactLinks"><span>Email <b>available soon</b></span><span>GitHub <b>available soon</b></span><span>LinkedIn <b>available soon</b></span></div></div><form onSubmit={e=>e.preventDefault()}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Message<textarea required placeholder="Tell me a little about your idea..." rows={4}/></label><button className="button primary" type="submit">Send message <span>↗</span></button></form></div></section>
  <footer><span>© 2026 Malek Al Bikawi</span><span>Built with curiosity <i>✦</i></span><button onClick={()=>scroll('home')}>Back to top ↑</button></footer>
 </main>
}
